src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreateAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Photo;

    /**
 * @ORM\Column(type="string", length=255)
 */
    private $Region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $product;


    private $Other;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="Annonce")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeInterface $CreateAt): self
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->Region;
    }

    public function setRegion(string $Region): self
    {
        $this->Region = $Region;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getOther(): ?string
    {
        return $this->Other;
    }

    public function setOther(string $Other): self
    {
        $this->Other = $Other;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getProduct()
    {
        return $this->product;
    }

    public function setProduct($product): self
    {
        $this->product = $product;
        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\AnnonceType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class MainController extends Controller
{
    private $annonceAll;

    /**
     * @Route("/main", name="main")
     */

    public function index(EntityManagerInterface $em)
    {
        $annonceAll = $em->getRepository(Product::class)->findAll();



        return $this->render('main/index.html.twig', [
//            'controller_name' => 'MainController',
        'annonceAll' => $annonceAll
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home(){
        return $this->render('main/home.html.twig');
    }

//    /**
//     * @Route("/main/compte", name="compte")
//     */
//    public function connect(){
//        return $this->render('main/compte.html.twig');
//    }

    /**
     * @Route("/main", name="annonce_show")
     */
    public function show(){

        $annonces = new Product();

        $form = $this->createForm(AnnonceType::class, $annonces);


        return $this->render('main/show.html.twig', [
            'annonce' => $annonces,
            'article' => $form->createView()
        ]);

    }
}

templates/main/home.html.twig
{% extends 'base.html.twig' %}


{% block body %}

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Hello{% endblock %}

{% block body %}
    <section class="Annonces">
        {% for annonce in annonceAll  %}
        <article >
            <br>
            <h1 style="text-align: center">Annonces</h1>
            <br><hr><br>
            <div class="content">
                <P><h2>{{ annonce.title }}</h2></P>

                <h4>Categorie</h4>
                <P>{{ annonce.category }}</P>
                <img src="{{asset('uploads/brochures/' ~ annonce.photo)}}" alt="">
                <br>
                <div class="metadata">Posté le {{ annonce.createAt|date }}</div>
                <br>
                <p>{{ annonce.description }}</p>

                <a href="{{ path('annonce_show') }}" class="btn btn-primary">Voir l'annonce</a>
            </div>
        </article>
        {% endfor %}
    </section>
{% endblock %}

templates/main/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <article >
        <h2>Annonce</h2>
        <div class="metadata">Posté le 19/07/2018</div>
        <div class="content">
            <img src="{{asset('uploads/brochures/' ~ annonce.photo)}}" alt="">
            <P>Description</P>
            <a href="{{ path('annonce_show') }}" class="btn btn-primary">Voir l'annonce</a>
        </div>
    </article>
    <hr>
    <p>Description en détail</p>




{% endblock %}